### ISSUE TITLE
How should I integrate Nodes into my design process?

### ISSUE THREAD

**Issue by Darelbi** [sebas77/Svelto-ECS#2]
I really not understand why nodes are there and how can I keep into account them when designin the game, I feel like I'm missing something really important. There are some obscure points that probably are handled in automatic by Svelto:

1) Implementors are instantiated by?
2) Implementors are injected according to what..nodes?

**Comment by Darelbi** [comment]
What I don't get (and that is probably a feature), is that 

I can have a Implementor implementing components A,B,C, while at same time a Node map components B,C,D. How exactly svelto make sure an Entity have N components, and that all those components are used by some Node?

**Comment by sebas77** [comment]
The simplest way to see nodes vs components is this:

- Components must be designed as part of an entity. The components, starting from their names, are thought to compose an entity.
- Nodes instead are linked to the engines. Nodes are how engines see entitites.

In this way you totally decouple the design of your entities from the design of your engines. 

You build an entity always through the BuildEntity function (see my last article). The BuildEntity needs the list of implementors. You can create implementors on the spot or pass them as monobehaviour, it doesn't matter.

As you realised, components are not object in Svelto.ECS, they are just interfaces, so an object must implement them. These objects are the implementors.

About the last question, it doesn't matter for you, that Svelto.ECS magic. If you don't implement some components needed for an Entity, Svelto.ECS will tell you with an exception in run-time.
